version: '3.9'
services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile # Ensure this Dockerfile is inside the ./backend directory
    ports:
      - "8080:8080"
    env_file:
      - .env.development.local
    environment:
      - PORT=8080
      - NODE_ENV=development
      - MONGO_HOST=mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: main
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-data:/data/db'
      - './docker-config/mongo-init-auth.js:/docker-entrypoint-initdb.d/mongo-init-auth.js:ro'
volumes:
  mongo-data: